### ISSUE TITLE
Issues building third_party/v8 with GCC 6.3

### ISSUE THREAD

**Issue by discordiasoftware** [Metrological/cobalt#72]
Hi, I've been trying to get master to build with a GCC 6.3 based cross-compiler, host is x86_64, target is arm64. I've encountered innumerable issues, but the latest is more difficult. There's an error building the v8 library for the target platform (truncated due to length):

```
../../third_party/v8/src/builtins/builtins.cc: In constructor 'v8::internal::{anonymous}::OffHeapTrampolineGenerator::OffHeapTrampolineGenerator(v8::internal::Isolate*)':
../../third_party/v8/src/builtins/builtins.cc:340:60: error: use of deleted function 'v8::internal::MacroAssembler::MacroAssembler(v8::internal::Isolate*, const v8::internal::AssemblerOptions&, v8::internal::CodeObjectRequired, std::unique_ptr<v8::internal::AssemblerBuffer>)'
               ExternalAssemblerBuffer(buffer_, kBufferSize)) {}
                                                            ^
In file included from ../../third_party/v8/src/codegen/macro-assembler.h:39:0,
                 from ../../third_party/v8/src/codegen/macro-assembler-inl.h:9,
                 from ../../third_party/v8/src/builtins/builtins.cc:11:
../../third_party/v8/src/codegen/arm64/macro-assembler-arm64.h:1443:25: note: 'v8::internal::MacroAssembler::MacroAssembler(v8::internal::Isolate*, const v8::internal::AssemblerOptions&, v8::internal::CodeObjectRequired, std::unique_ptr<v8::internal::AssemblerBuffer>)' is implicitly deleted because the default definition would be ill-formed:
   using TurboAssembler::TurboAssembler;
                         ^~~~~~~~~~~~~~
../../third_party/v8/src/codegen/arm64/macro-assembler-arm64.h:1443:25: error: use of deleted function 'v8::internal::TurboAssembler::TurboAssembler(v8::internal::Isolate*, const v8::internal::AssemblerOptions&, v8::internal::CodeObjectRequired, std::unique_ptr<v8::internal::AssemblerBuffer>)'
../../third_party/v8/src/codegen/arm64/macro-assembler-arm64.h:154:29: note: 'v8::internal::TurboAssembler::TurboAssembler(v8::internal::Isolate*, const v8::internal::AssemblerOptions&, v8::internal::CodeObjectRequired, std::unique_ptr<v8::internal::AssemblerBuffer>)' is implicitly deleted because the default definition would be ill-formed:
   using TurboAssemblerBase::TurboAssemblerBase;
                             ^~~~~~~~~~~~~~~~~~
../../third_party/v8/src/codegen/arm64/macro-assembler-arm64.h:154:29: error: no matching function for call to 'v8::internal::CPURegList::CPURegList()'
In file included from ../../third_party/v8/src/codegen/register-arch.h:16:0,
                 from ../../third_party/v8/src/codegen/interface-descriptors.h:11,
                 from ../../third_party/v8/src/builtins/builtins-descriptors.h:9,
                 from ../../third_party/v8/src/builtins/builtins.cc:8:
```

This appears to be the issue reported here: https://github.com/nodejs/node-v8/issues/103

I don't expect a solution to this problem, as this lies with the Cobalt developers. My question is, what GCC version has this fork been developed for? Are there any detailed instructions on the platform to use? I am trying to evaluate whether use of this fork is appropriate for my project. Thanks.
